### ISSUE TITLE
move from glamor to jss

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-mille#53]
- [x] Move `hoc` into `packages` (#57)
- [x] Use it into `invoices` (#58)
- [x] Move from `glamor` to `jss` (css-in-js) (#61 )
